version: '3.7'

services:
  db:
    container_name: dbfr
    image: postgres:13.0-alpine
    ports:
      - 5432:5432
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3.12.5-management
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
  celery:
    build: src/.
    container_name: celery
    command: celery -A config worker -l INFO
    env_file:
      - .env
  backend:
    build: src/.
    container_name: backend
    command: /app/entrypoint.sh
    ports:
      - "8000:8000"
    env_file:
      - .env